version: '3.8'
services:
  users:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=users_db
      - DB_DATABASE=users
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: 'php artisan serve'
    volumes:
      - .:/app
    ports:
      - 8050:8000
    depends_on:
      - users_db
    networks:
      - user_network
      
  users_db:
    image: mysql:5.7.22
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./storage/dbdata:/var/lib/mysql/
    ports:
      - 33068:3306
    networks:
      - user_network

networks:
  user_network:
    driver: bridge
    