version: '3.7'
services:
  frontend: 
    image: antoniopapa1991/admin-frontend
    depends_on:
      - backend
    networks:
      - app
  
  backend:
    container_name: admin-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST=db
      DB_DATABASE=admin
      DB_USERNAME=root
      DB_PASSWORD=root
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app
  
  db:
    container_name: admin_db
    image: mysql:5.7.22
    environment:
      MYSQL_USER=root
      MYSQL_PASSWORD=root
      MYSQL_DATABASE=admin
      MYSQL_ROOT_PASSWORD=root
    volumes:
      - .dbdata:/var/lib/mysql/
    ports:
      - 33066:3306
    networks:
      - app

networks:
  app: